#!/bin/bash -x

# Example showning how to use easy2ban with Qmail maillog
# to look for password failures.
#

BAN_DIR="var/ban";
BAN_TIME=5;  # (minutes)
MONITOR_TIME=5;  # (minutes)
MAX_HITS=4;
LAWS="qr/LOGIN FAILED/";
CMD="sudo qtail imap4-ssl |";

mkdir -p var/ban

easy2ban -v -c "$CMD" -L "$LAWS" -x $MAX_HITS -i $MONITOR_TIME -d $BAN_DIR -b $BAN_TIME
