#!/bin/bash -x

# Example showning how to use easy2ban with Apache
# error_log to look for failures.
#

BAN_DIR="var/ban";
BAN_TIME=5;  # (minutes)
MONITOR_TIME=5;  # (minutes)
MAX_HITS=5;
LAWS="qr/Failed password/, qr/authentication failure/, qr/[Ii]nvalid user/"
CMD="sudo tail -qf /var/log/secure |";

mkdir -p var/ban

easy2ban -v -c "$CMD" -L "$LAWS" -x $MAX_HITS -i $MONITOR_TIME -d $BAN_DIR -b $BAN_TIME
