#!/bin/bash -x

#
# Attempts to access root using ssh are banned for
# a long time period.
#

BAN_DIR="var/ban";
BAN_TIME=1440;  # (minutes)
MONITOR_TIME=5;  # (minutes)
MAX_HITS=2;
LAWS="qr/Failed password for root/"
CMD="sudo tail -qf /var/log/secure |";

mkdir -p var/ban

easy2ban -v -c "$CMD" -L "$LAWS" -x $MAX_HITS -i $MONITOR_TIME -d $BAN_DIR -b $BAN_TIME
