#!/bin/bash

# Example showning how to use easy2ban with Apache
# error_log to look for failures.

BAN_DIR="var/ban";
LOG_FILE="var/log/easy2ban";
BAN_TIME=5;  # (minutes)
MONITOR_TIME=5;  # (minutes)
MAX_HITS=10;
LAWS="qr/File does not exist/";
CMD="sudo tail -qf /home/*/*/log/error_log |";
PATH="bin:$PATH";
NAME=`basename $0`;

mkdir -p var/ban
mkdir -p var/log

#easy2ban -v -c "$CMD" -L "$LAWS" -x $MAX_HITS -i $MONITOR_TIME -d $BAN_DIR -b $BAN_TIME -n "$NAME"
easy2ban -c "$CMD" -L "$LAWS" -x $MAX_HITS -i $MONITOR_TIME -d $BAN_DIR -b $BAN_TIME -n "$NAME" 2>&1 >> $LOG_FILE &
